// <auto-generated />
using Balanced_Soccer_Team_Generator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Balanced_Soccer_Team_Generator.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251119180832_Seed100Players")]
    partial class Seed100Players
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Balanced_Soccer_Team_Generator.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BallControl")
                        .HasColumnType("int");

                    b.Property<int>("DefensiveAwareness")
                        .HasColumnType("int");

                    b.Property<int>("Dribbling")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OverallScore")
                        .HasColumnType("int");

                    b.Property<int>("PassingAccuracy")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("Shooting")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BallControl = 10,
                            DefensiveAwareness = 6,
                            Dribbling = 10,
                            Name = "Lionel Messi",
                            OverallScore = 0,
                            PassingAccuracy = 10,
                            Rank = 0,
                            Shooting = 10
                        },
                        new
                        {
                            Id = 2,
                            BallControl = 9,
                            DefensiveAwareness = 7,
                            Dribbling = 9,
                            Name = "Cristiano Ronaldo",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 10
                        },
                        new
                        {
                            Id = 3,
                            BallControl = 9,
                            DefensiveAwareness = 7,
                            Dribbling = 10,
                            Name = "Kylian Mbappé",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 9
                        },
                        new
                        {
                            Id = 4,
                            BallControl = 8,
                            DefensiveAwareness = 6,
                            Dribbling = 7,
                            Name = "Erling Haaland",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 10
                        },
                        new
                        {
                            Id = 5,
                            BallControl = 9,
                            DefensiveAwareness = 8,
                            Dribbling = 8,
                            Name = "Kevin De Bruyne",
                            OverallScore = 0,
                            PassingAccuracy = 10,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 6,
                            BallControl = 10,
                            DefensiveAwareness = 6,
                            Dribbling = 10,
                            Name = "Neymar Jr",
                            OverallScore = 0,
                            PassingAccuracy = 9,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 7,
                            BallControl = 9,
                            DefensiveAwareness = 6,
                            Dribbling = 9,
                            Name = "Mohamed Salah",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 9
                        },
                        new
                        {
                            Id = 8,
                            BallControl = 9,
                            DefensiveAwareness = 7,
                            Dribbling = 8,
                            Name = "Harry Kane",
                            OverallScore = 0,
                            PassingAccuracy = 9,
                            Rank = 0,
                            Shooting = 10
                        },
                        new
                        {
                            Id = 9,
                            BallControl = 9,
                            DefensiveAwareness = 8,
                            Dribbling = 9,
                            Name = "Jude Bellingham",
                            OverallScore = 0,
                            PassingAccuracy = 9,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 10,
                            BallControl = 9,
                            DefensiveAwareness = 6,
                            Dribbling = 10,
                            Name = "Vinícius Jr",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 11,
                            BallControl = 9,
                            DefensiveAwareness = 6,
                            Dribbling = 8,
                            Name = "Robert Lewandowski",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 10
                        },
                        new
                        {
                            Id = 12,
                            BallControl = 9,
                            DefensiveAwareness = 7,
                            Dribbling = 9,
                            Name = "Luka Modrić",
                            OverallScore = 0,
                            PassingAccuracy = 10,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 13,
                            BallControl = 9,
                            DefensiveAwareness = 7,
                            Dribbling = 8,
                            Name = "Karim Benzema",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 9
                        },
                        new
                        {
                            Id = 14,
                            BallControl = 8,
                            DefensiveAwareness = 7,
                            Dribbling = 8,
                            Name = "Bruno Fernandes",
                            OverallScore = 0,
                            PassingAccuracy = 9,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 15,
                            BallControl = 8,
                            DefensiveAwareness = 7,
                            Dribbling = 9,
                            Name = "Sadio Mané",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 16,
                            BallControl = 9,
                            DefensiveAwareness = 7,
                            Dribbling = 9,
                            Name = "Antoine Griezmann",
                            OverallScore = 0,
                            PassingAccuracy = 9,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 17,
                            BallControl = 9,
                            DefensiveAwareness = 8,
                            Dribbling = 9,
                            Name = "Bernardo Silva",
                            OverallScore = 0,
                            PassingAccuracy = 9,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 18,
                            BallControl = 9,
                            DefensiveAwareness = 6,
                            Dribbling = 9,
                            Name = "Phil Foden",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 19,
                            BallControl = 8,
                            DefensiveAwareness = 9,
                            Dribbling = 7,
                            Name = "Rodri",
                            OverallScore = 0,
                            PassingAccuracy = 10,
                            Rank = 0,
                            Shooting = 6
                        },
                        new
                        {
                            Id = 20,
                            BallControl = 8,
                            DefensiveAwareness = 7,
                            Dribbling = 8,
                            Name = "João Cancelo",
                            OverallScore = 0,
                            PassingAccuracy = 9,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 21,
                            BallControl = 9,
                            DefensiveAwareness = 6,
                            Dribbling = 9,
                            Name = "Bukayo Saka",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 22,
                            BallControl = 9,
                            DefensiveAwareness = 6,
                            Dribbling = 8,
                            Name = "Martin Ødegaard",
                            OverallScore = 0,
                            PassingAccuracy = 10,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 23,
                            BallControl = 7,
                            DefensiveAwareness = 9,
                            Dribbling = 7,
                            Name = "Declan Rice",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 6
                        },
                        new
                        {
                            Id = 24,
                            BallControl = 7,
                            DefensiveAwareness = 10,
                            Dribbling = 6,
                            Name = "Virgil van Dijk",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 6
                        },
                        new
                        {
                            Id = 25,
                            BallControl = 9,
                            DefensiveAwareness = 5,
                            Dribbling = 8,
                            Name = "Trent Alexander-Arnold",
                            OverallScore = 0,
                            PassingAccuracy = 10,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 26,
                            BallControl = 6,
                            DefensiveAwareness = 10,
                            Dribbling = 5,
                            Name = "Alisson Becker",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 3
                        },
                        new
                        {
                            Id = 27,
                            BallControl = 7,
                            DefensiveAwareness = 9,
                            Dribbling = 6,
                            Name = "Ederson Moraes",
                            OverallScore = 0,
                            PassingAccuracy = 9,
                            Rank = 0,
                            Shooting = 4
                        },
                        new
                        {
                            Id = 28,
                            BallControl = 7,
                            DefensiveAwareness = 9,
                            Dribbling = 6,
                            Name = "Rúben Dias",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 5
                        },
                        new
                        {
                            Id = 29,
                            BallControl = 9,
                            DefensiveAwareness = 6,
                            Dribbling = 9,
                            Name = "Jack Grealish",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 30,
                            BallControl = 8,
                            DefensiveAwareness = 6,
                            Dribbling = 9,
                            Name = "Marcus Rashford",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 9
                        },
                        new
                        {
                            Id = 31,
                            BallControl = 7,
                            DefensiveAwareness = 10,
                            Dribbling = 6,
                            Name = "Casemiro",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 32,
                            BallControl = 8,
                            DefensiveAwareness = 8,
                            Dribbling = 7,
                            Name = "Bruno Guimarães",
                            OverallScore = 0,
                            PassingAccuracy = 9,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 33,
                            BallControl = 9,
                            DefensiveAwareness = 6,
                            Dribbling = 9,
                            Name = "Son Heung-min",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 9
                        },
                        new
                        {
                            Id = 34,
                            BallControl = 9,
                            DefensiveAwareness = 5,
                            Dribbling = 8,
                            Name = "James Maddison",
                            OverallScore = 0,
                            PassingAccuracy = 9,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 35,
                            BallControl = 8,
                            DefensiveAwareness = 6,
                            Dribbling = 8,
                            Name = "Kai Havertz",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 36,
                            BallControl = 7,
                            DefensiveAwareness = 10,
                            Dribbling = 6,
                            Name = "Thiago Silva",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 5
                        },
                        new
                        {
                            Id = 37,
                            BallControl = 8,
                            DefensiveAwareness = 7,
                            Dribbling = 8,
                            Name = "Enzo Fernández",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 6
                        },
                        new
                        {
                            Id = 38,
                            BallControl = 8,
                            DefensiveAwareness = 5,
                            Dribbling = 9,
                            Name = "Raheem Sterling",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 39,
                            BallControl = 7,
                            DefensiveAwareness = 6,
                            Dribbling = 7,
                            Name = "Dominic Calvert-Lewin",
                            OverallScore = 0,
                            PassingAccuracy = 6,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 40,
                            BallControl = 9,
                            DefensiveAwareness = 5,
                            Dribbling = 9,
                            Name = "Luis Díaz",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 41,
                            BallControl = 9,
                            DefensiveAwareness = 7,
                            Dribbling = 9,
                            Name = "Pedri",
                            OverallScore = 0,
                            PassingAccuracy = 9,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 42,
                            BallControl = 8,
                            DefensiveAwareness = 8,
                            Dribbling = 8,
                            Name = "Gavi",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 6
                        },
                        new
                        {
                            Id = 43,
                            BallControl = 9,
                            DefensiveAwareness = 7,
                            Dribbling = 9,
                            Name = "Frenkie de Jong",
                            OverallScore = 0,
                            PassingAccuracy = 9,
                            Rank = 0,
                            Shooting = 6
                        },
                        new
                        {
                            Id = 44,
                            BallControl = 6,
                            DefensiveAwareness = 10,
                            Dribbling = 5,
                            Name = "Ronald Araújo",
                            OverallScore = 0,
                            PassingAccuracy = 6,
                            Rank = 0,
                            Shooting = 5
                        },
                        new
                        {
                            Id = 45,
                            BallControl = 9,
                            DefensiveAwareness = 7,
                            Dribbling = 8,
                            Name = "Ilkay Gündogan",
                            OverallScore = 0,
                            PassingAccuracy = 9,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 46,
                            BallControl = 9,
                            DefensiveAwareness = 5,
                            Dribbling = 10,
                            Name = "Ousmane Dembélé",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 47,
                            BallControl = 10,
                            DefensiveAwareness = 6,
                            Dribbling = 10,
                            Name = "Jamal Musiala",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 48,
                            BallControl = 8,
                            DefensiveAwareness = 9,
                            Dribbling = 7,
                            Name = "Joshua Kimmich",
                            OverallScore = 0,
                            PassingAccuracy = 9,
                            Rank = 0,
                            Shooting = 6
                        },
                        new
                        {
                            Id = 49,
                            BallControl = 9,
                            DefensiveAwareness = 5,
                            Dribbling = 9,
                            Name = "Leroy Sané",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 50,
                            BallControl = 8,
                            DefensiveAwareness = 7,
                            Dribbling = 7,
                            Name = "Thomas Müller",
                            OverallScore = 0,
                            PassingAccuracy = 9,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 51,
                            BallControl = 8,
                            DefensiveAwareness = 6,
                            Dribbling = 8,
                            Name = "Victor Osimhen",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 9
                        },
                        new
                        {
                            Id = 52,
                            BallControl = 9,
                            DefensiveAwareness = 6,
                            Dribbling = 10,
                            Name = "Khvicha Kvaratskhelia",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 53,
                            BallControl = 8,
                            DefensiveAwareness = 6,
                            Dribbling = 9,
                            Name = "Federico Chiesa",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 54,
                            BallControl = 9,
                            DefensiveAwareness = 5,
                            Dribbling = 9,
                            Name = "Paulo Dybala",
                            OverallScore = 0,
                            PassingAccuracy = 9,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 55,
                            BallControl = 8,
                            DefensiveAwareness = 7,
                            Dribbling = 8,
                            Name = "Lautaro Martínez",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 9
                        },
                        new
                        {
                            Id = 56,
                            BallControl = 8,
                            DefensiveAwareness = 9,
                            Dribbling = 8,
                            Name = "Nicolo Barella",
                            OverallScore = 0,
                            PassingAccuracy = 9,
                            Rank = 0,
                            Shooting = 6
                        },
                        new
                        {
                            Id = 57,
                            BallControl = 8,
                            DefensiveAwareness = 7,
                            Dribbling = 7,
                            Name = "Hakan Çalhanoğlu",
                            OverallScore = 0,
                            PassingAccuracy = 9,
                            Rank = 0,
                            Shooting = 9
                        },
                        new
                        {
                            Id = 58,
                            BallControl = 9,
                            DefensiveAwareness = 5,
                            Dribbling = 10,
                            Name = "Rafael Leão",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 59,
                            BallControl = 7,
                            DefensiveAwareness = 5,
                            Dribbling = 6,
                            Name = "Krzysztof Piątek",
                            OverallScore = 0,
                            PassingAccuracy = 6,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 60,
                            BallControl = 8,
                            DefensiveAwareness = 5,
                            Dribbling = 9,
                            Name = "Serge Gnabry",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 61,
                            BallControl = 9,
                            DefensiveAwareness = 6,
                            Dribbling = 8,
                            Name = "Marco Reus",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 62,
                            BallControl = 9,
                            DefensiveAwareness = 5,
                            Dribbling = 10,
                            Name = "Jadon Sancho",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 63,
                            BallControl = 7,
                            DefensiveAwareness = 6,
                            Dribbling = 6,
                            Name = "Niclas Füllkrug",
                            OverallScore = 0,
                            PassingAccuracy = 6,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 64,
                            BallControl = 7,
                            DefensiveAwareness = 9,
                            Dribbling = 6,
                            Name = "Mats Hummels",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 5
                        },
                        new
                        {
                            Id = 65,
                            BallControl = 9,
                            DefensiveAwareness = 6,
                            Dribbling = 9,
                            Name = "Julian Brandt",
                            OverallScore = 0,
                            PassingAccuracy = 9,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 66,
                            BallControl = 9,
                            DefensiveAwareness = 6,
                            Dribbling = 9,
                            Name = "Ángel Di María",
                            OverallScore = 0,
                            PassingAccuracy = 9,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 67,
                            BallControl = 7,
                            DefensiveAwareness = 8,
                            Dribbling = 7,
                            Name = "Leandro Paredes",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 6
                        },
                        new
                        {
                            Id = 68,
                            BallControl = 8,
                            DefensiveAwareness = 5,
                            Dribbling = 9,
                            Name = "Giovanni Reyna",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 69,
                            BallControl = 7,
                            DefensiveAwareness = 5,
                            Dribbling = 7,
                            Name = "André Silva",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 70,
                            BallControl = 8,
                            DefensiveAwareness = 4,
                            Dribbling = 9,
                            Name = "Youssoufa Moukoko",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 71,
                            BallControl = 8,
                            DefensiveAwareness = 5,
                            Dribbling = 9,
                            Name = "Christian Pulisic",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 72,
                            BallControl = 9,
                            DefensiveAwareness = 8,
                            Dribbling = 10,
                            Name = "Alphonso Davies",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 6
                        },
                        new
                        {
                            Id = 73,
                            BallControl = 8,
                            DefensiveAwareness = 5,
                            Dribbling = 8,
                            Name = "Jonathan David",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 74,
                            BallControl = 7,
                            DefensiveAwareness = 5,
                            Dribbling = 6,
                            Name = "Cyle Larin",
                            OverallScore = 0,
                            PassingAccuracy = 6,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 75,
                            BallControl = 7,
                            DefensiveAwareness = 6,
                            Dribbling = 8,
                            Name = "Ismaël Koné",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 6
                        },
                        new
                        {
                            Id = 76,
                            BallControl = 5,
                            DefensiveAwareness = 9,
                            Dribbling = 4,
                            Name = "Milan Borjan",
                            OverallScore = 0,
                            PassingAccuracy = 6,
                            Rank = 0,
                            Shooting = 3
                        },
                        new
                        {
                            Id = 77,
                            BallControl = 8,
                            DefensiveAwareness = 5,
                            Dribbling = 9,
                            Name = "Hirving Lozano",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 78,
                            BallControl = 7,
                            DefensiveAwareness = 9,
                            Dribbling = 6,
                            Name = "Edson Álvarez",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 5
                        },
                        new
                        {
                            Id = 79,
                            BallControl = 7,
                            DefensiveAwareness = 6,
                            Dribbling = 7,
                            Name = "Raúl Jiménez",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 80,
                            BallControl = 7,
                            DefensiveAwareness = 8,
                            Dribbling = 7,
                            Name = "Weston McKennie",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 6
                        },
                        new
                        {
                            Id = 81,
                            BallControl = 8,
                            DefensiveAwareness = 5,
                            Dribbling = 8,
                            Name = "Sergiño Dest",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 5
                        },
                        new
                        {
                            Id = 82,
                            BallControl = 7,
                            DefensiveAwareness = 9,
                            Dribbling = 6,
                            Name = "Tyler Adams",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 5
                        },
                        new
                        {
                            Id = 83,
                            BallControl = 6,
                            DefensiveAwareness = 10,
                            Dribbling = 5,
                            Name = "Giorgio Chiellini",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 4
                        },
                        new
                        {
                            Id = 84,
                            BallControl = 9,
                            DefensiveAwareness = 5,
                            Dribbling = 9,
                            Name = "Carlos Vela",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 9
                        },
                        new
                        {
                            Id = 85,
                            BallControl = 9,
                            DefensiveAwareness = 5,
                            Dribbling = 9,
                            Name = "Lorenzo Insigne",
                            OverallScore = 0,
                            PassingAccuracy = 9,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 86,
                            BallControl = 8,
                            DefensiveAwareness = 5,
                            Dribbling = 8,
                            Name = "Federico Bernardeschi",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 87,
                            BallControl = 9,
                            DefensiveAwareness = 4,
                            Dribbling = 8,
                            Name = "Xherdan Shaqiri",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 88,
                            BallControl = 8,
                            DefensiveAwareness = 5,
                            Dribbling = 8,
                            Name = "Cucho Hernández",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 89,
                            BallControl = 8,
                            DefensiveAwareness = 5,
                            Dribbling = 7,
                            Name = "Josef Martínez",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 9
                        },
                        new
                        {
                            Id = 90,
                            BallControl = 9,
                            DefensiveAwareness = 5,
                            Dribbling = 9,
                            Name = "Riqui Puig",
                            OverallScore = 0,
                            PassingAccuracy = 9,
                            Rank = 0,
                            Shooting = 6
                        },
                        new
                        {
                            Id = 91,
                            BallControl = 9,
                            DefensiveAwareness = 5,
                            Dribbling = 10,
                            Name = "Thiago Almada",
                            OverallScore = 0,
                            PassingAccuracy = 9,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 92,
                            BallControl = 7,
                            DefensiveAwareness = 5,
                            Dribbling = 6,
                            Name = "Brandon Vazquez",
                            OverallScore = 0,
                            PassingAccuracy = 6,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 93,
                            BallControl = 7,
                            DefensiveAwareness = 7,
                            Dribbling = 7,
                            Name = "Paul Arriola",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 6
                        },
                        new
                        {
                            Id = 94,
                            BallControl = 7,
                            DefensiveAwareness = 6,
                            Dribbling = 7,
                            Name = "Jordan Morris",
                            OverallScore = 0,
                            PassingAccuracy = 6,
                            Rank = 0,
                            Shooting = 8
                        },
                        new
                        {
                            Id = 95,
                            BallControl = 8,
                            DefensiveAwareness = 6,
                            Dribbling = 8,
                            Name = "Djordje Mihailovic",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 96,
                            BallControl = 7,
                            DefensiveAwareness = 7,
                            Dribbling = 6,
                            Name = "Damir Kreilach",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 97,
                            BallControl = 9,
                            DefensiveAwareness = 6,
                            Dribbling = 9,
                            Name = "Emanuel Reynoso",
                            OverallScore = 0,
                            PassingAccuracy = 9,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 98,
                            BallControl = 8,
                            DefensiveAwareness = 6,
                            Dribbling = 8,
                            Name = "Jesús Ferreira",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 99,
                            BallControl = 6,
                            DefensiveAwareness = 10,
                            Dribbling = 5,
                            Name = "Walker Zimmerman",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 5
                        },
                        new
                        {
                            Id = 100,
                            BallControl = 7,
                            DefensiveAwareness = 9,
                            Dribbling = 6,
                            Name = "Miles Robinson",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
