// <auto-generated />
using Balanced_Soccer_Team_Generator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Balanced_Soccer_Team_Generator.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251119175538_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Balanced_Soccer_Team_Generator.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BallControl")
                        .HasColumnType("int");

                    b.Property<int>("DefensiveAwareness")
                        .HasColumnType("int");

                    b.Property<int>("Dribbling")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OverallScore")
                        .HasColumnType("int");

                    b.Property<int>("PassingAccuracy")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("Shooting")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BallControl = 8,
                            DefensiveAwareness = 6,
                            Dribbling = 8,
                            Name = "Alex",
                            OverallScore = 0,
                            PassingAccuracy = 7,
                            Rank = 0,
                            Shooting = 7
                        },
                        new
                        {
                            Id = 2,
                            BallControl = 6,
                            DefensiveAwareness = 7,
                            Dribbling = 7,
                            Name = "Blake",
                            OverallScore = 0,
                            PassingAccuracy = 6,
                            Rank = 0,
                            Shooting = 6
                        },
                        new
                        {
                            Id = 3,
                            BallControl = 9,
                            DefensiveAwareness = 7,
                            Dribbling = 8,
                            Name = "Casey",
                            OverallScore = 0,
                            PassingAccuracy = 8,
                            Rank = 0,
                            Shooting = 9
                        },
                        new
                        {
                            Id = 4,
                            BallControl = 5,
                            DefensiveAwareness = 5,
                            Dribbling = 5,
                            Name = "Drew",
                            OverallScore = 0,
                            PassingAccuracy = 5,
                            Rank = 0,
                            Shooting = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
